version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c "nginx -g 'daemon off;'" 
    ports:
      - 20080:80
    depends_on:
      - backend
  backend:
    build: flask
    environment: 
      - FLASK_SERVER_PORT=9091
    command: python server.py
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo  
  mongo:
    image: mongo
